version: '3'

services:
  webserver:
    platform: linux/amd64
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volume/nginx/conf/:/etc/nginx/conf.d/:rw
      - ./volume/nginx/html/:/usr/share/nginx/html:rw
      - ./volume/certbot/www/:/var/www/certbot/:rw
      - ./volume/certbot/conf/:/etc/nginx/ssl/:rw
     
  certbot:
    platform: linux/amd64
    image: certbot/certbot
    volumes:
      - ./volume/certbot/www/:/var/www/certbot/:rw
      - ./volume/certbot/conf/:/etc/letsencrypt/:rw
